### ISSUE TITLE
Har qanday vaziyatda ham  "commit" lar soni 1 ta bo'lmasligi kerak...

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#1]
Sababi agar biron-bir xato qilib qo'ysangizu buni keyinchalik bilib qolsangiz to'g'rilash uchun ketadigan vaqtni kamaytiradi bu. Va siz yuborgan har bir "commit" xuddi tarixga muhrlangandek bo'ladi, payti kelganda osongina ortga qayta olasiz...
![image](https://user-images.githubusercontent.com/99461357/164485441-74fe98ce-31e5-4b60-b6ac-b2b82c0adcbe.png)

**Comment by kamolazohidova** [comment]
ho'p
