### ISSUE TITLE
Linklar linkligi bilinishi kerak.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#10]
`h3` ichidagi linklarga `:hover` holatini berib qo'ying.
![image](https://user-images.githubusercontent.com/99461357/164497146-f7971f8e-5d7b-40db-831b-68bcd31310f4.png)

**Comment by kamolazohidova** [comment]
https://prnt.sc/aGh29_hG5jaJ

**Comment by kamolazohidova** [comment]
togrlandi😊
