### ISSUE TITLE
"Dark Mode"  rejimida `input` ning `::placeholder` rangi o'zgarmayapti.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#11]
![image](https://user-images.githubusercontent.com/99461357/164497509-7a960f5a-f8cf-4109-b643-6fbbeecea17b.png)

**Comment by kamolazohidova** [comment]
men placeholderni rangi ozgarishini bilmagandim...
to'g'rlab qo'yaman :)
