### ISSUE TITLE
"Dark Mode" rejimida  "yarim oy" ikonkasi "semirmasligi" kerak.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#12]
Oddiy holatda:
![image](https://user-images.githubusercontent.com/99461357/164498079-77000cb6-b247-4471-86e4-254393007de7.png)
"Dark Mode" holatida:
![image](https://user-images.githubusercontent.com/99461357/164498252-ac09b288-3ab2-4f45-abce-c53a77406ea7.png)

**Comment by kamolazohidova** [comment]
o'zi oy semiz ekanda.....men ozdirolmadim

**Comment by MIRZOULUGBEK9008** [comment]
> o'zi oy semiz ekanda.....men ozdirolmadim

Oy semiz emas, harakat qilib ko'ring agar to'g'rilay olmasangiz yordamlashaman...
