### ISSUE TITLE
"Dark Mode"  `button` ning shrifti maketdan farq qilmoqda.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#13]
**Maketda**
![image](https://user-images.githubusercontent.com/99461357/164498704-977b3783-3a0f-41e5-b599-33622353c472.png)
**Sizda**
![image](https://user-images.githubusercontent.com/99461357/164498835-5b0e8681-ff98-4384-b1df-bb7b1253472d.png)

**Comment by kamolazohidova** [comment]
https://prnt.sc/FeLPFoL4_JRo
https://prnt.sc/o62Q2xqV601y
menda ayb yoq maket bilan kelisholmadi VsCode😉

**Comment by MIRZOULUGBEK9008** [comment]
> https://prnt.sc/FeLPFoL4_JRo https://prnt.sc/o62Q2xqV601y menda ayb yoq maket bilan kelisholmadi VsCode😉

Bu yerda shrift stillarini to'g'ri olgan faqat `font-family:;` sini yana berib qo'yasiz, chunki `body` dan olmayapti.
