### ISSUE TITLE
"country.html" ning `background-color:;` i makedan farq qilmoqda.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#14]
**Maketda**
![image](https://user-images.githubusercontent.com/99461357/164499525-866a9348-7d38-4643-b4ae-c7ea9b005b60.png)
**Sizda**
![image](https://user-images.githubusercontent.com/99461357/164499609-01e093ba-3481-4050-b9c4-93289eb77c9a.png)

**Comment by kamolazohidova** [comment]
menimcha rootga berishda adashbman..... To'g'rlab qoydim🙂

**Comment by MIRZOULUGBEK9008** [comment]
> menimcha rootga berishda adashbman..... To'g'rlab qoydim🙂

To'g'rilanmapti...
