### ISSUE TITLE
#tavsiya

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#15]
Sayt "Dark Mode" ga o'tganiga ba'zi elementlarning rangi tez almashyapdi sababi ularga `transition:;` berilmagan `body` ga berilgan `transition`  ta'sir qilmasa demak alohida berish kerak. Ikkinchi variant yoki  `transition`  berish kerak hammasiga(tez o'zgaryotganiga) yoki umuman bermaslik kerak...

html  kodda  ortiqcha probel(space) bo'lmasligi kerak... umumiy kod yozilishida..

Sayt tuzilib bo'lgandan keyin, ekranni kichiklashtirib va kattalashtirib ko'ring (zoom in, zoom out) ekran kichraygan elementlarning qisilishini ko'p kuzatdim.

**Comment by kamolazohidova** [comment]
transion bergandim :rootga ham bodyga ham alohida linkga ham

**Comment by MIRZOULUGBEK9008** [comment]
> transion bergandim :rootga ham bodyga ham alohida linkga ham

Har bir o'zgarayotganiga ham bering..
