### ISSUE TITLE
Hech qachon `tarnsition:;` ni   qiymatini `all`  qilmang...

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#16]
Sababi brauzer kerak bo'lmagan narsalarga ham `transition` qo'shadi natijda  `:focus` holatidagi   "outline" stillari ham `transition` bilan paydo bo'ladi va hunuk ko'rinadi...
![image](https://user-images.githubusercontent.com/99461357/164566502-db34b5fa-8169-4ab2-9e39-e8de2bd33b5a.png)

**Comment by kamolazohidova** [comment]
aniq belgilangandi ease qo'shmaganmga shekkili qoshib qoydim👌
