### ISSUE TITLE
"Commit"  nomi doimo bosh(katta) harf bilan boshlanadi.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#2]
Commit ayni bir ma'noga ega bo'lish kerak va buyruq shaklida yozilishi kerak...
![image](https://user-images.githubusercontent.com/99461357/164485911-c9867093-6010-4a24-8b1e-1cf0b785bc72.png)

**Comment by kamolazohidova** [comment]
Ho'p🥴
