### ISSUE TITLE
html  validatorda chiqqan xatoni to'g'rilang.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#4]
Siz sarlavhadan foydalanmaganingiz uchun  `div` elementidan foydalaning deyilyapti.. `section` ning o'rniga
![image](https://user-images.githubusercontent.com/99461357/164487257-bdfc1399-6abb-4e76-aa8d-490520f966de.png)

**Comment by kamolazohidova** [comment]
bu ogohlantirishku... men headinglarni qoshish kerak deb oylamabman shu sababli qoshmagandim🙃

**Comment by MIRZOULUGBEK9008** [comment]
> bu ogohlantirishku... men headinglarni qoshish kerak deb oylamabman shu sababli qoshmagandim🙃

shuni `div` ga almashtrib qo'ysangiz shu ogohlantirish ham chiqmaydi :)
