### ISSUE TITLE
Agar stil berilmasa  `class` lar bo'sh qolmasin.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#5]
https://github.com/kamolazohidova/Zk_Countries/blob/5d4107d177df38e728657e7686927f502dfd9a0f/css/style.css#L210

**Comment by kamolazohidova** [comment]
sezasizlarmikin deb qoldirgandim😊
to'g'rladim kormey qolbman 😉
