### ISSUE TITLE
.svg ning joyi  "img" nomli papkaning ichida bo'ladi.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#6]
Shriftlar joylashgan papkaga svg ikonkani joylash- xuddi Alini to'nini Valiga kiydirmoqqa o'xshaydi. :)
![image](https://user-images.githubusercontent.com/99461357/164489856-63f2e7b5-32b5-4a24-8875-07ae7219f9ce.png)

**Comment by kamolazohidova** [comment]
Uzurasz🙈🙊
