### ISSUE TITLE
`:focus` holatidagi "default" stillar "default" ligicha qolmasligi kerak..

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#7]
Sayt dizayniga to'g'ri kelmagani uchun ushbu stillarni to'g'rilash kerak...
![image](https://user-images.githubusercontent.com/99461357/164492097-fda61782-5dbd-4e5a-b3f3-f337d8f182e4.png)

**Comment by kamolazohidova** [comment]
shoshilib qolbman🙃
togrlab qoydim
