### ISSUE TITLE
Ekran kichrayganda elementlar yopishib qolishini oldini oling.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#8]
![image](https://user-images.githubusercontent.com/99461357/164492731-c0a80d55-a31c-4f9d-b485-36ab9c297f29.png)
![image](https://user-images.githubusercontent.com/99461357/164493566-0fde02a0-54f5-45f8-b94b-d145049befce.png)

**Comment by kamolazohidova** [comment]
responsive qilishni aytyapszda siz men uni bilmiman hali😕

**Comment by MIRZOULUGBEK9008** [comment]
> responsive qilishni aytyapszda siz men uni bilmiman hali😕

Bu responsive ga aloqasi yo'q faqat ozgina `padding:;`  yoki `margin:;`  bilan hal qilsa bo'ladi...
