### ISSUE TITLE
Ekran kichrayganda `h3` elementi pastga(yangi qatorga) tushmasligi kerak va o'rab turuvchi idishi kichraymasligi(qisilmasligi) kerak.

### ISSUE THREAD

**Issue by MIRZOULUGBEK9008** [kamolazohidova/Zk_Countries#9]
![image](https://user-images.githubusercontent.com/99461357/164495319-abafe7f0-88ca-4ffc-9057-1c0cb0793e86.png)

**Comment by kamolazohidova** [comment]
men axr kichik ekranga moslashtirishni bilmaymanda......Ishlam kallamay qoldi lekn, shu darajada kop issues yozilishini endi kordm :)

**Comment by MIRZOULUGBEK9008** [comment]
> men axr kichik ekranga moslashtirishni bilmaymanda......Ishlam kallamay qoldi lekn, shu darajada kop issues yozilishini endi kordm :)

Buni ha responsive ga aloqasi yo'q. Bu matn bo'lgani uchun  `class` iga  `white-space: no-wrap;` qilib qo'ysangiz masala hal.
